apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-usage-calculator
  namespace: gpu-sizing
spec:
  template:
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: calculator
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
              nvidia.com/gpu: 1
